services:
  workspace:
    tty: true
    build:
      context: .
      args:
        PUID: "${PUID:-1000}"
        PGID: "${PGID:-1000}"
    volumes:
      - .:/var/www/html
      - ~/.composer:/home/user/.composer
